'use strict';
// let number = parseFloat('56.5px');
// console.log(number);
// let num = parseFloat('8.5px');
// let num2 = parseFloat('9.45px');
// alert(num + num2);
// let number = 46;
// number += 5;
// console.log(number)
// let num = 47;
// num += 7;
// num -= 18;
// num *= 10;
// num /= 15;
// alert(num);
// let num = 4;
// console.log(num++);
// console.log(num);
// let num1 = 4;
// console.log(++num1);
// console.log(num1);
let num = 10;
console.log(num++);
console.log(num);
console.log(++num);
console.log(num);
console.log(--num);
console.log(num);
alert(num);